name: Daemons
version: @version@-@apitype@-@apiversion@
description: An empty example plugin for Spigot with Gradle
authors: [Akoot]
website: https://github.com/ReneHollander/empty-spigot-plugin

main: com.Akoot.daemons.Daemons

commands:
    Test:
        description: Test command.
        aliases: [tst]
    Nick:
        description: Set nickname.
        aliases: [nickname, nic]
    Make:
        description: Make someone do something.
        aliases: [mk]
    gm:
        description: Changed gamemode.
        aliases: []