name: Daemons
version: @version@-@apitype@-@apiversion@
description: Daemons
authors: [Akoot]
website: https://google.com

main: com.Akoot.daemons.Daemons

commands:
    Test:
        description: Test command.
        aliases: [tst]
    Nick:
        description: Set nickname.
        aliases: [nickname, nic]
    Make:
        description: Make someone do something.
        aliases: [mk]
    gm:
        description: Changed gamemode.
        aliases: []
    Playtime:
        description: Shows playtime.
        aliases: [pt, playt]
    SetLore:
        description: Sets the lore of the item in hand.
        aliases: [sl, lore]
    Rename:
        description: Rename item in hand
        aliases: [rn]
    SetMOTD:
        description: Sets the MOTD of the server.
        aliases: [smotd]
    AddMOTD:
        description: Adds to the MOTD of the server.
        aliases: [amotd]
    Raw:
        description: Send a Raw message (No prefix)
        aliases: []
    Say:
        description: Say a message through the server
        aliases: []
    Profile:
        description: Profile command.
        aliases: [p, prof]
    Redeem:
        description: Redeem command.
        aliases: [rd, rdeem]
    Shutdown:
        description: Shuts down the server.
        aliases: [stop]