name: Daemons
version: @version@-@apitype@-@apiversion@
description: An empty example plugin for Spigot with Gradle
authors: [Akoot]
website: https://github.com/ReneHollander/empty-spigot-plugin

main: com.Akoot.daemons.Daemons
